#!/usr/bin/python

import sys
from beast import roughness_of_actuation, safety_of_navigation


USAGE = """usage: beast range.csv wrench.csv output_dir
range.csv: TOBEDEFINED
wrench.csv: TOBEDEFINED
"""

if __name__ == '__main__':

    print "BEAST PI computation"

    arg_len = 4
    if len(sys.argv) != arg_len:
        print USAGE
        sys.exit(-1)

    range_path, wrench_path, output_folder_path = sys.argv[1:]

    print "Running pi roughness_of_actuation"
    is_ok = roughness_of_actuation.run_pi(wrench_path, output_folder_path)
    if not is_ok == 0:
        sys.exit(is_ok)

    print "Running pi safety_of_navigation"
    is_ok = safety_of_navigation.run_pi(range_path, output_folder_path)
    if not is_ok == 0:
        sys.exit(is_ok)

    print "All computation done"
    sys.exit(0)
