#!/usr/bin/python

import sys
from beast import trolley_handle_smoothness


USAGE = """usage: beast wrench.csv output_dir
wrench.csv: TOBEDEFINED
"""

if __name__ == '__main__':

    print "BEAST PI computation"

    arg_len = 3
    if len(sys.argv) != arg_len:
        print USAGE
        sys.exit(-1)

    wrench_path, output_folder_path = sys.argv[1:]

    print "Running pi trolley_handle_smoothness"
    is_ok = trolley_handle_smoothness.run_pi(wrench_path, output_folder_path)
    if not is_ok == 0:
        sys.exit(is_ok)

    print "All computation done"
    sys.exit(0)
