#!/usr/bin/python

import sys
from beast import roughness_of_actuation, safety_of_navigation, time_to_grip_handle, time_to_checkpoint_1, time_to_checkpoint_2, time_to_checkpoint_3, time_to_checkpoint_4, time_to_checkpoint_5, capability_level


USAGE = """usage: beast event.csv distance.csv wrench.csv condition.yaml output_dir
event.csv: TOBEDEFINED
distance.csv: TOBEDEFINED
wrench.csv: TOBEDEFINED
condition.yaml: TOBEDEFINED
"""

if __name__ == '__main__':

    print "BEAST PI computation"

    arg_len = 6
    if len(sys.argv) != arg_len:
        print USAGE
        sys.exit(-1)

    event_path, distance_path, wrench_path, condition_path, output_folder_path = sys.argv[1:]

    print "Running pi roughness_of_actuation"
    is_ok = roughness_of_actuation.run_pi(wrench_path, output_folder_path)
    if not is_ok == 0:
        sys.exit(is_ok)

    print "Running pi safety_of_navigation"
    is_ok = safety_of_navigation.run_pi(distance_path, output_folder_path)
    if not is_ok == 0:
        sys.exit(is_ok)

    print "Running pi time_to_grip_handle"
    is_ok = time_to_grip_handle.run_pi(event_path, condition_path, output_folder_path)
    if not is_ok == 0:
        sys.exit(is_ok)

    print "Running pi time_to_checkpoint_1"
    is_ok = time_to_checkpoint_1.run_pi(event_path, condition_path, output_folder_path)
    if not is_ok == 0:
        sys.exit(is_ok)

    print "Running pi time_to_checkpoint_2"
    is_ok = time_to_checkpoint_2.run_pi(event_path, condition_path, output_folder_path)
    if not is_ok == 0:
        sys.exit(is_ok)

    print "Running pi time_to_checkpoint_3"
    is_ok = time_to_checkpoint_3.run_pi(event_path, condition_path, output_folder_path)
    if not is_ok == 0:
        sys.exit(is_ok)

    print "Running pi time_to_checkpoint_4"
    is_ok = time_to_checkpoint_4.run_pi(event_path, condition_path, output_folder_path)
    if not is_ok == 0:
        sys.exit(is_ok)

    print "Running pi time_to_checkpoint_5"
    is_ok = time_to_checkpoint_5.run_pi(event_path, condition_path, output_folder_path)
    if not is_ok == 0:
        sys.exit(is_ok)

    print "Running pi capability_level"
    is_ok = capability_level.run_pi(event_path, condition_path, output_folder_path)
    if not is_ok == 0:
        sys.exit(is_ok)

    print "All computation done"
    sys.exit(0)
