#!/usr/bin/python
import os
import sys
import subprocess


if __name__ == '__main__':
    base_dir = os.path.dirname(os.path.realpath(__file__))

    benchmark_type = os.getenv('BENCHMARK_TYPE')
    script_name = os.getenv('SCRIPT_NAME')

    subprocess.call([os.path.join(base_dir, benchmark_type.lower(), script_name.lower()+'.py')] + sys.argv[1:])